### ISSUE TITLE
Support special 'Transifex' branch

### ISSUE THREAD

**Issue by matthewjackowski** [transifex/txgh#24]
Have a special git branch for interacting with Transifex*
We could merge everything to a 'transifex' branch and wait for translations before merging that to the release branch but this causes a delay and introduces coordination difficulties (what if some of the pieces are ready to go but others aren't? what if we need to roll back a piece?).

**Comment by mkllnk** [comment]
I use a transifex branch for my project. Since it is open source, I gave Transifex the URL of the resource on GitHub to update automatically. It points to the transifex branch:

    https://raw.githubusercontent.com/openfoodfoundation/openfoodnetwork/transifex/config/locales/en.yml

I did not set up the GitHub hook to trigger txgh. I just set up the Transifex hook to commit to the transifex branch.
```yml
txgh:
    github:
        repos:
            openfoodfoundation/openfoodnetwork:
                api_username: "***"
                api_token: "***"
                branch: "transifex"
    transifex:
        projects:
            open-food-network:
                tx_config: "config/tx.config"
                api_username: "***"
                api_password: "***"
                push_translations_to: "openfoodfoundation/openfoodnetwork"
```

We merge the latest translations into our master branch and update the transifex branch whenever we release a new version or start a 'string freeze'. This way the translators have time to translate a release while the developers keep playing with the master branch.

I guess you can't avoid a translation delay unless you let people translate experimental versions that change all the time. That could be a lot of wasted translator time.
