### ISSUE TITLE
Multiproject from transifex to one github repo.

### ISSUE THREAD

**Issue by susannamaxon** [transifex/txgh#66]
I have been trying to set txgh up for many projects on transifex to one github repo.
I can't find a way to to this does txgh support this?

What I find logical is setting this up in txgh.yml

txgh:
    github:
       repos:
           yy/xx.mm
            api_username: "<%= ENV['GITHUB_USERNAME'] %>"
            api_token: "<%= ENV['GITHUB_TOKEN'] %>"
            webhook_secret: "<%= ENV['GITHUB_WEBHOOK_SECRET'] %>"
            branch: "develop"
            push_source_to: "xx-project,yy-project"
   transifex:
        projects:
            xx-project:
                tx_config: "config/txxx.config"
                api_username: "<%= ENV['TX_USERNAME'] %>"
                api_password: "<%= ENV['TX_PASSWORD'] %>"
                push_translations_to: "yy/xx.mm"
            yy-project:
                tx_config: "config/txyy.config"
                api_username: "<%= ENV['TX_USERNAME'] %>"
                api_password: "<%= ENV['TX_PASSWORD'] %>"
                push_translations_to: "yy/xx.mm"

**Comment by matthewjackowski** [comment]
Hi @susannamaxon !  So I *think* the issue you are having is that you are assuming that you would need two separate tx.config files.  If you look at the multi-project tests here: https://github.com/transifex/txgh/blob/master/spec/tx_config_multi_project_spec.rb 
You'll notice that resources for both projects are in a single tx.config.

Quite frankly I haven't given it much thought as to what the best approach is for this (assuming that you have the tx.configs under some sort  of source control). 

It would be great to get your feedback and we could consider extending the app to be more flexible in this regard.

**Comment by susannamaxon** [comment]
Thanks @matthewjackowski 
Thas right, I thought I needed two tx.config.
We created our own project that use your docker image and our txgh.yml and tx.config.

**Comment by susannamaxon** [comment]
Hæ @matthewjackowski 

I have now a working code that transport translation from two projects in Transifex to one repo in github. But it is only pushing to one prjocet from Github to Transifex and that is the projecttwo as it is last in the txgh.yml file.

The problem is the settings for github in txgh.yml file as I have same repository that I want to push to two different projects.

What I have done is creating two configfiles as one file with two project was not working for me.
txgh.yml is like this:

``` 
txgh:
  github:
    repos:
      company/translationservice:
        api_username: "<%= ENV['GITHUB_USERNAME'] %>"
        api_token: "<%= ENV['GITHUB_TOKEN'] %>"
        push_source_to: "projectone"
        branch: "<%= ENV['GITHUB_BRANCH'] %>"
        webhook_secret: "<%= ENV['GITHUB_WEBHOOK_SECRET'] %>"
      company/translationservice:
        api_username: "<%= ENV['GITHUB_USERNAME'] %>"
        api_token: "<%= ENV['GITHUB_TOKEN'] %>"
        push_source_to: "projecttwo"
        branch: "<%= ENV['GITHUB_BRANCH'] %>"
        webhook_secret: "<%= ENV['GITHUB_WEBHOOK_SECRET'] %>"
  transifex:
    projects:
      projectone:
        tx_config: "config/txprojectone.config"
        api_username: "<%= ENV['TX_USERNAME'] %>"
        api_password: "<%= ENV['TX_PASSWORD'] %>"
        push_translations_to: "company/translationservice"
        webhook_secret: "<%= ENV['TX_WEBHOOK_SECRET'] %>"
      projecttwo:
        tx_config: "config/txprojecttwo.config"
        api_username: "<%= ENV['TX_USERNAME'] %>"
        api_password: "<%= ENV['TX_PASSWORD'] %>"
        push_translations_to: "company/translationservice"
        webhook_secret: "<%= ENV['TX_WEBHOOK_SECRET'] %>"
```
txprojecttwo.config:
```
[main]
host = https://www.transifex.com
lang_map =

# Create one such section per resource
[projecttwo.defaultjson]
file_filter = translations/projecttwo/<lang>/default.json
source_file = transifex/projecttwo/default.json
source_lang = en
type = JSON

[projecttwo.testjson]
file_filter = translations/projecttwo/<lang>/test.json
source_file = transifex/projecttwo/test.json
source_lang = en
type = JSON
```
txprojectone.config:
```
[main]
host = https://www.transifex.com
lang_map =

# Create one such section per resource

[projectone.projectonejson]
file_filter = translations/projectone/<lang>/projectone.json
source_file = transifex/projectone/projectone.json
source_lang = en
type = JSON
```
